http_server:
  port: "8080"
  max_header_bytes: 1
  read_timeout: 10s
  write_timeout: 10s

postgresQl:
  username: "postgres"
  password: "marta2010"
  db_name: "socialNetwork"
  host: "127.0.0.1"
  port: "5432"

jwt_token: "Amenosubaruboshinomicoto: Ryugo"