http_server:
  port: "8080"
  max_header_bytes: 1
  read_timeout: 10s
  write_timeout: 10s

postgres:
  username: "az3lff"
  password: "SergeyAndKirill"
  db_name: "social_network_for_programmers"

jwt_token: "Amenosubaruboshinomicoto: Ryugo"