http_server:
  port: "8080"
  max_header_bytes: 1
  read_timeout: 10s
  write_timeout: 10s

postgresQl:
  username: "az3lff"
  password: "SergeyAndKirill"
  db_name: "social_network_for_programmers"
  host: "127.0.0.1"
  port: "5432"

auth_email:
  username: "az3lff@gmail.com"
  password: "ibuh nrfk qoui mxvk"
  host: "smtp.gmail.com"
  port: "587"

secret_key: "Amenosubaruboshinomicoto: Ryugo"